// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package ai.asleep.asleep_sdk_flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object TransportPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class AudioSessionOptionMessage(val raw: Int) {
  DUCK_OTHERS(0),
  ALLOW_AIR_PLAY(1),
  ALLOW_BLUETOOTH(2),
  ALLOW_BLUETOOTH_A2DP(3);

  companion object {
    fun ofRaw(raw: Int): AudioSessionOptionMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetupMessage (
  val apiKey: String,
  val baseUrl: String? = null,
  val callbackUrl: String? = null,
  val service: String? = null,
  val enableOnDeviceAnalysis: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetupMessage {
      val apiKey = pigeonVar_list[0] as String
      val baseUrl = pigeonVar_list[1] as String?
      val callbackUrl = pigeonVar_list[2] as String?
      val service = pigeonVar_list[3] as String?
      val enableOnDeviceAnalysis = pigeonVar_list[4] as Boolean
      return SetupMessage(apiKey, baseUrl, callbackUrl, service, enableOnDeviceAnalysis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      baseUrl,
      callbackUrl,
      service,
      enableOnDeviceAnalysis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SetupMessage
    return TransportPigeonUtils.deepEquals(this.apiKey, other.apiKey) && TransportPigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && TransportPigeonUtils.deepEquals(this.callbackUrl, other.callbackUrl) && TransportPigeonUtils.deepEquals(this.service, other.service) && TransportPigeonUtils.deepEquals(this.enableOnDeviceAnalysis, other.enableOnDeviceAnalysis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + TransportPigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + TransportPigeonUtils.deepHash(this.callbackUrl)
    result = 31 * result + TransportPigeonUtils.deepHash(this.service)
    result = 31 * result + TransportPigeonUtils.deepHash(this.enableOnDeviceAnalysis)
    return result
  }
  override fun toString(): String {
    return "SetupMessage(apiKey=$apiKey, baseUrl=$baseUrl, callbackUrl=$callbackUrl, service=$service, enableOnDeviceAnalysis=$enableOnDeviceAnalysis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfigurationMessage (
  val apiKey: String,
  val userId: String? = null,
  val baseUrl: String? = null,
  val callbackUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigurationMessage {
      val apiKey = pigeonVar_list[0] as String
      val userId = pigeonVar_list[1] as String?
      val baseUrl = pigeonVar_list[2] as String?
      val callbackUrl = pigeonVar_list[3] as String?
      return ConfigurationMessage(apiKey, userId, baseUrl, callbackUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      apiKey,
      userId,
      baseUrl,
      callbackUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConfigurationMessage
    return TransportPigeonUtils.deepEquals(this.apiKey, other.apiKey) && TransportPigeonUtils.deepEquals(this.userId, other.userId) && TransportPigeonUtils.deepEquals(this.baseUrl, other.baseUrl) && TransportPigeonUtils.deepEquals(this.callbackUrl, other.callbackUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.apiKey)
    result = 31 * result + TransportPigeonUtils.deepHash(this.userId)
    result = 31 * result + TransportPigeonUtils.deepHash(this.baseUrl)
    result = 31 * result + TransportPigeonUtils.deepHash(this.callbackUrl)
    return result
  }
  override fun toString(): String {
    return "ConfigurationMessage(apiKey=$apiKey, userId=$userId, baseUrl=$baseUrl, callbackUrl=$callbackUrl)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NotificationMessage (
  val title: String? = null,
  val text: String? = null,
  val icon: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationMessage {
      val title = pigeonVar_list[0] as String?
      val text = pigeonVar_list[1] as String?
      val icon = pigeonVar_list[2] as String?
      return NotificationMessage(title, text, icon)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      text,
      icon,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NotificationMessage
    return TransportPigeonUtils.deepEquals(this.title, other.title) && TransportPigeonUtils.deepEquals(this.text, other.text) && TransportPigeonUtils.deepEquals(this.icon, other.icon)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.title)
    result = 31 * result + TransportPigeonUtils.deepHash(this.text)
    result = 31 * result + TransportPigeonUtils.deepHash(this.icon)
    return result
  }
  override fun toString(): String {
    return "NotificationMessage(title=$title, text=$text, icon=$icon)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TrackingMessage (
  val androidNotification: NotificationMessage? = null,
  val iosAudioSessionOptions: List<AudioSessionOptionMessage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrackingMessage {
      val androidNotification = pigeonVar_list[0] as NotificationMessage?
      val iosAudioSessionOptions = pigeonVar_list[1] as List<AudioSessionOptionMessage>
      return TrackingMessage(androidNotification, iosAudioSessionOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      androidNotification,
      iosAudioSessionOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrackingMessage
    return TransportPigeonUtils.deepEquals(this.androidNotification, other.androidNotification) && TransportPigeonUtils.deepEquals(this.iosAudioSessionOptions, other.iosAudioSessionOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.androidNotification)
    result = 31 * result + TransportPigeonUtils.deepHash(this.iosAudioSessionOptions)
    return result
  }
  override fun toString(): String {
    return "TrackingMessage(androidNotification=$androidNotification, iosAudioSessionOptions=$iosAudioSessionOptions)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RestoreMessage (
  val hasActiveSession: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RestoreMessage {
      val hasActiveSession = pigeonVar_list[0] as Boolean
      return RestoreMessage(hasActiveSession)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasActiveSession,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RestoreMessage
    return TransportPigeonUtils.deepEquals(this.hasActiveSession, other.hasActiveSession)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.hasActiveSession)
    return result
  }
  override fun toString(): String {
    return "RestoreMessage(hasActiveSession=$hasActiveSession)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BatteryOptimizationMessage (
  val exempted: Boolean,
  val platform: String,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatteryOptimizationMessage {
      val exempted = pigeonVar_list[0] as Boolean
      val platform = pigeonVar_list[1] as String
      val message = pigeonVar_list[2] as String?
      return BatteryOptimizationMessage(exempted, platform, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exempted,
      platform,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BatteryOptimizationMessage
    return TransportPigeonUtils.deepEquals(this.exempted, other.exempted) && TransportPigeonUtils.deepEquals(this.platform, other.platform) && TransportPigeonUtils.deepEquals(this.message, other.message)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.exempted)
    result = 31 * result + TransportPigeonUtils.deepHash(this.platform)
    result = 31 * result + TransportPigeonUtils.deepHash(this.message)
    return result
  }
  override fun toString(): String {
    return "BatteryOptimizationMessage(exempted=$exempted, platform=$platform, message=$message)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AnalysisRequestMessage (
  val status: String,
  val timestampMilliseconds: Long? = null,
  val resultJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnalysisRequestMessage {
      val status = pigeonVar_list[0] as String
      val timestampMilliseconds = pigeonVar_list[1] as Long?
      val resultJson = pigeonVar_list[2] as String?
      return AnalysisRequestMessage(status, timestampMilliseconds, resultJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      timestampMilliseconds,
      resultJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AnalysisRequestMessage
    return TransportPigeonUtils.deepEquals(this.status, other.status) && TransportPigeonUtils.deepEquals(this.timestampMilliseconds, other.timestampMilliseconds) && TransportPigeonUtils.deepEquals(this.resultJson, other.resultJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.status)
    result = 31 * result + TransportPigeonUtils.deepHash(this.timestampMilliseconds)
    result = 31 * result + TransportPigeonUtils.deepHash(this.resultJson)
    return result
  }
  override fun toString(): String {
    return "AnalysisRequestMessage(status=$status, timestampMilliseconds=$timestampMilliseconds, resultJson=$resultJson)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeEventMessage (
  val type: String,
  val payloadJson: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeEventMessage {
      val type = pigeonVar_list[0] as String
      val payloadJson = pigeonVar_list[1] as String
      return NativeEventMessage(type, payloadJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      payloadJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeEventMessage
    return TransportPigeonUtils.deepEquals(this.type, other.type) && TransportPigeonUtils.deepEquals(this.payloadJson, other.payloadJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + TransportPigeonUtils.deepHash(this.type)
    result = 31 * result + TransportPigeonUtils.deepHash(this.payloadJson)
    return result
  }
  override fun toString(): String {
    return "NativeEventMessage(type=$type, payloadJson=$payloadJson)"
  }
}
private open class TransportPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AudioSessionOptionMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetupMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigurationMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrackingMessage.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RestoreMessage.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatteryOptimizationMessage.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalysisRequestMessage.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeEventMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AudioSessionOptionMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is SetupMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ConfigurationMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NotificationMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TrackingMessage -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is RestoreMessage -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BatteryOptimizationMessage -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is AnalysisRequestMessage -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NativeEventMessage -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val TransportPigeonMethodCodec = StandardMethodCodec(TransportPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AsleepHostApi {
  fun setup(message: SetupMessage, callback: (Result<Unit>) -> Unit)
  fun configure(message: ConfigurationMessage, callback: (Result<Unit>) -> Unit)
  fun checkAndRestoreTracking(callback: (Result<RestoreMessage>) -> Unit)
  fun checkBatteryOptimization(callback: (Result<BatteryOptimizationMessage>) -> Unit)
  fun requestBatteryOptimizationExemption(callback: (Result<Boolean>) -> Unit)
  fun hasRequiredPermissions(callback: (Result<Boolean>) -> Unit)
  fun requestRequiredPermissions(callback: (Result<Boolean>) -> Unit)
  fun startTracking(message: TrackingMessage, callback: (Result<Unit>) -> Unit)
  fun resumeTracking(callback: (Result<Unit>) -> Unit)
  fun stopTracking(callback: (Result<Unit>) -> Unit)
  fun requestAnalysis(callback: (Result<AnalysisRequestMessage>) -> Unit)
  fun getReport(sessionId: String, callback: (Result<String>) -> Unit)
  fun getReportList(fromDate: String, toDate: String, callback: (Result<List<String>>) -> Unit)
  fun getAverageReport(fromDate: String, toDate: String, callback: (Result<String>) -> Unit)
  fun deleteSession(sessionId: String, callback: (Result<Unit>) -> Unit)
  fun setLoggingEnabled(enabled: Boolean, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by AsleepHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TransportPigeonCodec()
    }
    /** Sets up an instance of `AsleepHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AsleepHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.setup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as SetupMessage
            api.setup(messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as ConfigurationMessage
            api.configure(messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.checkAndRestoreTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkAndRestoreTracking{ result: Result<RestoreMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.checkBatteryOptimization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkBatteryOptimization{ result: Result<BatteryOptimizationMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestBatteryOptimizationExemption$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestBatteryOptimizationExemption{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.hasRequiredPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.hasRequiredPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestRequiredPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestRequiredPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.startTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as TrackingMessage
            api.startTracking(messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.resumeTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.resumeTracking{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.stopTracking$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopTracking{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestAnalysis$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestAnalysis{ result: Result<AnalysisRequestMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getReport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.getReport(sessionIdArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getReportList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fromDateArg = args[0] as String
            val toDateArg = args[1] as String
            api.getReportList(fromDateArg, toDateArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getAverageReport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val fromDateArg = args[0] as String
            val toDateArg = args[1] as String
            api.getAverageReport(fromDateArg, toDateArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(TransportPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.deleteSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.deleteSession(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.setLoggingEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            api.setLoggingEnabled(enabledArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(TransportPigeonUtils.wrapError(error))
              } else {
                reply.reply(TransportPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class TransportPigeonStreamHandler<T>(
    val wrapper: TransportPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface TransportPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}

abstract class EventsStreamHandler : TransportPigeonEventChannelWrapper<NativeEventMessage> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: EventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.asleep_sdk_flutter.AsleepEventChannelApi.events"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = TransportPigeonStreamHandler<NativeEventMessage>(streamHandler)
      EventChannel(messenger, channelName, TransportPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from TransportPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<NativeEventMessage>) {}

override fun onCancel(p0: Any?) {}
}
