// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum AudioSessionOptionMessage {
  duckOthers,
  allowAirPlay,
  allowBluetooth,
  allowBluetoothA2DP,
}

class SetupMessage {
  SetupMessage({
    required this.apiKey,
    this.baseUrl,
    this.callbackUrl,
    this.service,
    required this.enableOnDeviceAnalysis,
  });

  String apiKey;

  String? baseUrl;

  String? callbackUrl;

  String? service;

  bool enableOnDeviceAnalysis;

  List<Object?> _toList() {
    return <Object?>[
      apiKey,
      baseUrl,
      callbackUrl,
      service,
      enableOnDeviceAnalysis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SetupMessage decode(Object result) {
    result as List<Object?>;
    return SetupMessage(
      apiKey: result[0]! as String,
      baseUrl: result[1] as String?,
      callbackUrl: result[2] as String?,
      service: result[3] as String?,
      enableOnDeviceAnalysis: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SetupMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) &&
        _deepEquals(baseUrl, other.baseUrl) &&
        _deepEquals(callbackUrl, other.callbackUrl) &&
        _deepEquals(service, other.service) &&
        _deepEquals(enableOnDeviceAnalysis, other.enableOnDeviceAnalysis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SetupMessage(apiKey: $apiKey, baseUrl: $baseUrl, callbackUrl: $callbackUrl, service: $service, enableOnDeviceAnalysis: $enableOnDeviceAnalysis)';
  }
}

class ConfigurationMessage {
  ConfigurationMessage({
    required this.apiKey,
    this.userId,
    this.baseUrl,
    this.callbackUrl,
  });

  String apiKey;

  String? userId;

  String? baseUrl;

  String? callbackUrl;

  List<Object?> _toList() {
    return <Object?>[apiKey, userId, baseUrl, callbackUrl];
  }

  Object encode() {
    return _toList();
  }

  static ConfigurationMessage decode(Object result) {
    result as List<Object?>;
    return ConfigurationMessage(
      apiKey: result[0]! as String,
      userId: result[1] as String?,
      baseUrl: result[2] as String?,
      callbackUrl: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConfigurationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(apiKey, other.apiKey) &&
        _deepEquals(userId, other.userId) &&
        _deepEquals(baseUrl, other.baseUrl) &&
        _deepEquals(callbackUrl, other.callbackUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConfigurationMessage(apiKey: $apiKey, userId: $userId, baseUrl: $baseUrl, callbackUrl: $callbackUrl)';
  }
}

class NotificationMessage {
  NotificationMessage({this.title, this.text, this.icon});

  String? title;

  String? text;

  String? icon;

  List<Object?> _toList() {
    return <Object?>[title, text, icon];
  }

  Object encode() {
    return _toList();
  }

  static NotificationMessage decode(Object result) {
    result as List<Object?>;
    return NotificationMessage(
      title: result[0] as String?,
      text: result[1] as String?,
      icon: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(text, other.text) &&
        _deepEquals(icon, other.icon);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NotificationMessage(title: $title, text: $text, icon: $icon)';
  }
}

class TrackingMessage {
  TrackingMessage({
    this.androidNotification,
    required this.iosAudioSessionOptions,
  });

  NotificationMessage? androidNotification;

  List<AudioSessionOptionMessage> iosAudioSessionOptions;

  List<Object?> _toList() {
    return <Object?>[androidNotification, iosAudioSessionOptions];
  }

  Object encode() {
    return _toList();
  }

  static TrackingMessage decode(Object result) {
    result as List<Object?>;
    return TrackingMessage(
      androidNotification: result[0] as NotificationMessage?,
      iosAudioSessionOptions: (result[1]! as List<Object?>)
          .cast<AudioSessionOptionMessage>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrackingMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(androidNotification, other.androidNotification) &&
        _deepEquals(iosAudioSessionOptions, other.iosAudioSessionOptions);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrackingMessage(androidNotification: $androidNotification, iosAudioSessionOptions: $iosAudioSessionOptions)';
  }
}

class RestoreMessage {
  RestoreMessage({required this.hasActiveSession});

  bool hasActiveSession;

  List<Object?> _toList() {
    return <Object?>[hasActiveSession];
  }

  Object encode() {
    return _toList();
  }

  static RestoreMessage decode(Object result) {
    result as List<Object?>;
    return RestoreMessage(hasActiveSession: result[0]! as bool);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RestoreMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasActiveSession, other.hasActiveSession);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RestoreMessage(hasActiveSession: $hasActiveSession)';
  }
}

class BatteryOptimizationMessage {
  BatteryOptimizationMessage({
    required this.exempted,
    required this.platform,
    this.message,
  });

  bool exempted;

  String platform;

  String? message;

  List<Object?> _toList() {
    return <Object?>[exempted, platform, message];
  }

  Object encode() {
    return _toList();
  }

  static BatteryOptimizationMessage decode(Object result) {
    result as List<Object?>;
    return BatteryOptimizationMessage(
      exempted: result[0]! as bool,
      platform: result[1]! as String,
      message: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BatteryOptimizationMessage ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(exempted, other.exempted) &&
        _deepEquals(platform, other.platform) &&
        _deepEquals(message, other.message);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'BatteryOptimizationMessage(exempted: $exempted, platform: $platform, message: $message)';
  }
}

class AnalysisRequestMessage {
  AnalysisRequestMessage({
    required this.status,
    this.timestampMilliseconds,
    this.resultJson,
  });

  String status;

  int? timestampMilliseconds;

  String? resultJson;

  List<Object?> _toList() {
    return <Object?>[status, timestampMilliseconds, resultJson];
  }

  Object encode() {
    return _toList();
  }

  static AnalysisRequestMessage decode(Object result) {
    result as List<Object?>;
    return AnalysisRequestMessage(
      status: result[0]! as String,
      timestampMilliseconds: result[1] as int?,
      resultJson: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalysisRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) &&
        _deepEquals(timestampMilliseconds, other.timestampMilliseconds) &&
        _deepEquals(resultJson, other.resultJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalysisRequestMessage(status: $status, timestampMilliseconds: $timestampMilliseconds, resultJson: $resultJson)';
  }
}

class NativeEventMessage {
  NativeEventMessage({required this.type, required this.payloadJson});

  String type;

  String payloadJson;

  List<Object?> _toList() {
    return <Object?>[type, payloadJson];
  }

  Object encode() {
    return _toList();
  }

  static NativeEventMessage decode(Object result) {
    result as List<Object?>;
    return NativeEventMessage(
      type: result[0]! as String,
      payloadJson: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeEventMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) &&
        _deepEquals(payloadJson, other.payloadJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeEventMessage(type: $type, payloadJson: $payloadJson)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is AudioSessionOptionMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is SetupMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is ConfigurationMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NotificationMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is TrackingMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is RestoreMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is BatteryOptimizationMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is AnalysisRequestMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is NativeEventMessage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AudioSessionOptionMessage.values[value];
      case 130:
        return SetupMessage.decode(readValue(buffer)!);
      case 131:
        return ConfigurationMessage.decode(readValue(buffer)!);
      case 132:
        return NotificationMessage.decode(readValue(buffer)!);
      case 133:
        return TrackingMessage.decode(readValue(buffer)!);
      case 134:
        return RestoreMessage.decode(readValue(buffer)!);
      case 135:
        return BatteryOptimizationMessage.decode(readValue(buffer)!);
      case 136:
        return AnalysisRequestMessage.decode(readValue(buffer)!);
      case 137:
        return NativeEventMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

class AsleepHostApi {
  /// Constructor for [AsleepHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AsleepHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setup(SetupMessage message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.setup$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> configure(ConfigurationMessage message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<RestoreMessage> checkAndRestoreTracking() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.checkAndRestoreTracking$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as RestoreMessage;
  }

  Future<BatteryOptimizationMessage> checkBatteryOptimization() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.checkBatteryOptimization$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as BatteryOptimizationMessage;
  }

  Future<bool> requestBatteryOptimizationExemption() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestBatteryOptimizationExemption$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> hasRequiredPermissions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.hasRequiredPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<bool> requestRequiredPermissions() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestRequiredPermissions$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  Future<void> startTracking(TrackingMessage message) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.startTracking$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[message],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> resumeTracking() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.resumeTracking$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> stopTracking() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.stopTracking$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<AnalysisRequestMessage> requestAnalysis() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestAnalysis$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AnalysisRequestMessage;
  }

  Future<String> getReport(String sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getReport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<List<String>> getReportList(String fromDate, String toDate) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getReportList$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fromDate, toDate],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  Future<String> getAverageReport(String fromDate, String toDate) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getAverageReport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[fromDate, toDate],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  Future<void> deleteSession(String sessionId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.deleteSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[sessionId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> setLoggingEnabled(bool enabled) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.setLoggingEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[enabled],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

/// Returns a broadcast [Stream] of events from the `events` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<NativeEventMessage> events({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel eventsChannel = EventChannel(
    'dev.flutter.pigeon.asleep_sdk_flutter.AsleepEventChannelApi.events$instanceName',
    pigeonMethodCodec,
  );
  return eventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as NativeEventMessage;
  });
}
