// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum TransportPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum AudioSessionOptionMessage: Int, CaseIterable {
  case duckOthers = 0
  case allowAirPlay = 1
  case allowBluetooth = 2
  case allowBluetoothA2DP = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct SetupMessage: Hashable, CustomStringConvertible {
  var apiKey: String
  var baseUrl: String? = nil
  var callbackUrl: String? = nil
  var service: String? = nil
  var enableOnDeviceAnalysis: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SetupMessage? {
    let apiKey = pigeonVar_list[0] as! String
    let baseUrl: String? = nilOrValue(pigeonVar_list[1])
    let callbackUrl: String? = nilOrValue(pigeonVar_list[2])
    let service: String? = nilOrValue(pigeonVar_list[3])
    let enableOnDeviceAnalysis = pigeonVar_list[4] as! Bool

    return SetupMessage(
      apiKey: apiKey,
      baseUrl: baseUrl,
      callbackUrl: callbackUrl,
      service: service,
      enableOnDeviceAnalysis: enableOnDeviceAnalysis
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      baseUrl,
      callbackUrl,
      service,
      enableOnDeviceAnalysis,
    ]
  }
  static func == (lhs: SetupMessage, rhs: SetupMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.apiKey, rhs.apiKey) && TransportPigeonInternal.deepEquals(lhs.baseUrl, rhs.baseUrl) && TransportPigeonInternal.deepEquals(lhs.callbackUrl, rhs.callbackUrl) && TransportPigeonInternal.deepEquals(lhs.service, rhs.service) && TransportPigeonInternal.deepEquals(lhs.enableOnDeviceAnalysis, rhs.enableOnDeviceAnalysis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SetupMessage")
    TransportPigeonInternal.deepHash(value: apiKey, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: baseUrl, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: callbackUrl, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: service, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: enableOnDeviceAnalysis, hasher: &hasher)
  }

  public var description: String {
    return "SetupMessage(apiKey: \(String(describing: apiKey)), baseUrl: \(String(describing: baseUrl)), callbackUrl: \(String(describing: callbackUrl)), service: \(String(describing: service)), enableOnDeviceAnalysis: \(String(describing: enableOnDeviceAnalysis)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConfigurationMessage: Hashable, CustomStringConvertible {
  var apiKey: String
  var userId: String? = nil
  var baseUrl: String? = nil
  var callbackUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfigurationMessage? {
    let apiKey = pigeonVar_list[0] as! String
    let userId: String? = nilOrValue(pigeonVar_list[1])
    let baseUrl: String? = nilOrValue(pigeonVar_list[2])
    let callbackUrl: String? = nilOrValue(pigeonVar_list[3])

    return ConfigurationMessage(
      apiKey: apiKey,
      userId: userId,
      baseUrl: baseUrl,
      callbackUrl: callbackUrl
    )
  }
  func toList() -> [Any?] {
    return [
      apiKey,
      userId,
      baseUrl,
      callbackUrl,
    ]
  }
  static func == (lhs: ConfigurationMessage, rhs: ConfigurationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.apiKey, rhs.apiKey) && TransportPigeonInternal.deepEquals(lhs.userId, rhs.userId) && TransportPigeonInternal.deepEquals(lhs.baseUrl, rhs.baseUrl) && TransportPigeonInternal.deepEquals(lhs.callbackUrl, rhs.callbackUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConfigurationMessage")
    TransportPigeonInternal.deepHash(value: apiKey, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: userId, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: baseUrl, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: callbackUrl, hasher: &hasher)
  }

  public var description: String {
    return "ConfigurationMessage(apiKey: \(String(describing: apiKey)), userId: \(String(describing: userId)), baseUrl: \(String(describing: baseUrl)), callbackUrl: \(String(describing: callbackUrl)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NotificationMessage: Hashable, CustomStringConvertible {
  var title: String? = nil
  var text: String? = nil
  var icon: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NotificationMessage? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let text: String? = nilOrValue(pigeonVar_list[1])
    let icon: String? = nilOrValue(pigeonVar_list[2])

    return NotificationMessage(
      title: title,
      text: text,
      icon: icon
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      text,
      icon,
    ]
  }
  static func == (lhs: NotificationMessage, rhs: NotificationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.title, rhs.title) && TransportPigeonInternal.deepEquals(lhs.text, rhs.text) && TransportPigeonInternal.deepEquals(lhs.icon, rhs.icon)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NotificationMessage")
    TransportPigeonInternal.deepHash(value: title, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: text, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: icon, hasher: &hasher)
  }

  public var description: String {
    return "NotificationMessage(title: \(String(describing: title)), text: \(String(describing: text)), icon: \(String(describing: icon)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TrackingMessage: Hashable, CustomStringConvertible {
  var androidNotification: NotificationMessage? = nil
  var iosAudioSessionOptions: [AudioSessionOptionMessage]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TrackingMessage? {
    let androidNotification: NotificationMessage? = nilOrValue(pigeonVar_list[0])
    let iosAudioSessionOptions = pigeonVar_list[1] as! [AudioSessionOptionMessage]

    return TrackingMessage(
      androidNotification: androidNotification,
      iosAudioSessionOptions: iosAudioSessionOptions
    )
  }
  func toList() -> [Any?] {
    return [
      androidNotification,
      iosAudioSessionOptions,
    ]
  }
  static func == (lhs: TrackingMessage, rhs: TrackingMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.androidNotification, rhs.androidNotification) && TransportPigeonInternal.deepEquals(lhs.iosAudioSessionOptions, rhs.iosAudioSessionOptions)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("TrackingMessage")
    TransportPigeonInternal.deepHash(value: androidNotification, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: iosAudioSessionOptions, hasher: &hasher)
  }

  public var description: String {
    return "TrackingMessage(androidNotification: \(String(describing: androidNotification)), iosAudioSessionOptions: \(String(describing: iosAudioSessionOptions)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RestoreMessage: Hashable, CustomStringConvertible {
  var hasActiveSession: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RestoreMessage? {
    let hasActiveSession = pigeonVar_list[0] as! Bool

    return RestoreMessage(
      hasActiveSession: hasActiveSession
    )
  }
  func toList() -> [Any?] {
    return [
      hasActiveSession
    ]
  }
  static func == (lhs: RestoreMessage, rhs: RestoreMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.hasActiveSession, rhs.hasActiveSession)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RestoreMessage")
    TransportPigeonInternal.deepHash(value: hasActiveSession, hasher: &hasher)
  }

  public var description: String {
    return "RestoreMessage(hasActiveSession: \(String(describing: hasActiveSession)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BatteryOptimizationMessage: Hashable, CustomStringConvertible {
  var exempted: Bool
  var platform: String
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BatteryOptimizationMessage? {
    let exempted = pigeonVar_list[0] as! Bool
    let platform = pigeonVar_list[1] as! String
    let message: String? = nilOrValue(pigeonVar_list[2])

    return BatteryOptimizationMessage(
      exempted: exempted,
      platform: platform,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      exempted,
      platform,
      message,
    ]
  }
  static func == (lhs: BatteryOptimizationMessage, rhs: BatteryOptimizationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.exempted, rhs.exempted) && TransportPigeonInternal.deepEquals(lhs.platform, rhs.platform) && TransportPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BatteryOptimizationMessage")
    TransportPigeonInternal.deepHash(value: exempted, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: platform, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "BatteryOptimizationMessage(exempted: \(String(describing: exempted)), platform: \(String(describing: platform)), message: \(String(describing: message)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnalysisRequestMessage: Hashable, CustomStringConvertible {
  var status: String
  var timestampMilliseconds: Int64? = nil
  var resultJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalysisRequestMessage? {
    let status = pigeonVar_list[0] as! String
    let timestampMilliseconds: Int64? = nilOrValue(pigeonVar_list[1])
    let resultJson: String? = nilOrValue(pigeonVar_list[2])

    return AnalysisRequestMessage(
      status: status,
      timestampMilliseconds: timestampMilliseconds,
      resultJson: resultJson
    )
  }
  func toList() -> [Any?] {
    return [
      status,
      timestampMilliseconds,
      resultJson,
    ]
  }
  static func == (lhs: AnalysisRequestMessage, rhs: AnalysisRequestMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.status, rhs.status) && TransportPigeonInternal.deepEquals(lhs.timestampMilliseconds, rhs.timestampMilliseconds) && TransportPigeonInternal.deepEquals(lhs.resultJson, rhs.resultJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnalysisRequestMessage")
    TransportPigeonInternal.deepHash(value: status, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: timestampMilliseconds, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: resultJson, hasher: &hasher)
  }

  public var description: String {
    return "AnalysisRequestMessage(status: \(String(describing: status)), timestampMilliseconds: \(String(describing: timestampMilliseconds)), resultJson: \(String(describing: resultJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeEventMessage: Hashable, CustomStringConvertible {
  var type: String
  var payloadJson: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeEventMessage? {
    let type = pigeonVar_list[0] as! String
    let payloadJson = pigeonVar_list[1] as! String

    return NativeEventMessage(
      type: type,
      payloadJson: payloadJson
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      payloadJson,
    ]
  }
  static func == (lhs: NativeEventMessage, rhs: NativeEventMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return TransportPigeonInternal.deepEquals(lhs.type, rhs.type) && TransportPigeonInternal.deepEquals(lhs.payloadJson, rhs.payloadJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeEventMessage")
    TransportPigeonInternal.deepHash(value: type, hasher: &hasher)
    TransportPigeonInternal.deepHash(value: payloadJson, hasher: &hasher)
  }

  public var description: String {
    return "NativeEventMessage(type: \(String(describing: type)), payloadJson: \(String(describing: payloadJson)))"
  }
}

private class TransportPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AudioSessionOptionMessage(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return SetupMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return ConfigurationMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return NotificationMessage.fromList(self.readValue() as! [Any?])
    case 133:
      return TrackingMessage.fromList(self.readValue() as! [Any?])
    case 134:
      return RestoreMessage.fromList(self.readValue() as! [Any?])
    case 135:
      return BatteryOptimizationMessage.fromList(self.readValue() as! [Any?])
    case 136:
      return AnalysisRequestMessage.fromList(self.readValue() as! [Any?])
    case 137:
      return NativeEventMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TransportPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AudioSessionOptionMessage {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SetupMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ConfigurationMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NotificationMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? TrackingMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? RestoreMessage {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BatteryOptimizationMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? AnalysisRequestMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NativeEventMessage {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TransportPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TransportPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TransportPigeonCodecWriter(data: data)
  }
}

class TransportPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TransportPigeonCodec(readerWriter: TransportPigeonCodecReaderWriter())
}

var transportPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: TransportPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AsleepHostApi {
  func setup(message: SetupMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func configure(message: ConfigurationMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func checkAndRestoreTracking(completion: @escaping (Result<RestoreMessage, Error>) -> Void)
  func checkBatteryOptimization(completion: @escaping (Result<BatteryOptimizationMessage, Error>) -> Void)
  func requestBatteryOptimizationExemption(completion: @escaping (Result<Bool, Error>) -> Void)
  func hasRequiredPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func requestRequiredPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  func startTracking(message: TrackingMessage, completion: @escaping (Result<Void, Error>) -> Void)
  func resumeTracking(completion: @escaping (Result<Void, Error>) -> Void)
  func stopTracking(completion: @escaping (Result<Void, Error>) -> Void)
  func requestAnalysis(completion: @escaping (Result<AnalysisRequestMessage, Error>) -> Void)
  func getReport(sessionId: String, completion: @escaping (Result<String, Error>) -> Void)
  func getReportList(fromDate: String, toDate: String, completion: @escaping (Result<[String], Error>) -> Void)
  func getAverageReport(fromDate: String, toDate: String, completion: @escaping (Result<String, Error>) -> Void)
  func deleteSession(sessionId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func setLoggingEnabled(enabled: Bool, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AsleepHostApiSetup {
  static var codec: FlutterStandardMessageCodec { TransportPigeonCodec.shared }
  /// Sets up an instance of `AsleepHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AsleepHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.setup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! SetupMessage
        api.setup(message: messageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setupChannel.setMessageHandler(nil)
    }
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! ConfigurationMessage
        api.configure(message: messageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    let checkAndRestoreTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.checkAndRestoreTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkAndRestoreTrackingChannel.setMessageHandler { _, reply in
        api.checkAndRestoreTracking { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkAndRestoreTrackingChannel.setMessageHandler(nil)
    }
    let checkBatteryOptimizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.checkBatteryOptimization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkBatteryOptimizationChannel.setMessageHandler { _, reply in
        api.checkBatteryOptimization { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkBatteryOptimizationChannel.setMessageHandler(nil)
    }
    let requestBatteryOptimizationExemptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestBatteryOptimizationExemption\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestBatteryOptimizationExemptionChannel.setMessageHandler { _, reply in
        api.requestBatteryOptimizationExemption { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestBatteryOptimizationExemptionChannel.setMessageHandler(nil)
    }
    let hasRequiredPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.hasRequiredPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasRequiredPermissionsChannel.setMessageHandler { _, reply in
        api.hasRequiredPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      hasRequiredPermissionsChannel.setMessageHandler(nil)
    }
    let requestRequiredPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestRequiredPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestRequiredPermissionsChannel.setMessageHandler { _, reply in
        api.requestRequiredPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestRequiredPermissionsChannel.setMessageHandler(nil)
    }
    let startTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.startTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startTrackingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! TrackingMessage
        api.startTracking(message: messageArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startTrackingChannel.setMessageHandler(nil)
    }
    let resumeTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.resumeTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeTrackingChannel.setMessageHandler { _, reply in
        api.resumeTracking { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumeTrackingChannel.setMessageHandler(nil)
    }
    let stopTrackingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.stopTracking\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopTrackingChannel.setMessageHandler { _, reply in
        api.stopTracking { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopTrackingChannel.setMessageHandler(nil)
    }
    let requestAnalysisChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.requestAnalysis\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestAnalysisChannel.setMessageHandler { _, reply in
        api.requestAnalysis { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestAnalysisChannel.setMessageHandler(nil)
    }
    let getReportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getReport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getReportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        api.getReport(sessionId: sessionIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getReportChannel.setMessageHandler(nil)
    }
    let getReportListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getReportList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getReportListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fromDateArg = args[0] as! String
        let toDateArg = args[1] as! String
        api.getReportList(fromDate: fromDateArg, toDate: toDateArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getReportListChannel.setMessageHandler(nil)
    }
    let getAverageReportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.getAverageReport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAverageReportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let fromDateArg = args[0] as! String
        let toDateArg = args[1] as! String
        api.getAverageReport(fromDate: fromDateArg, toDate: toDateArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAverageReportChannel.setMessageHandler(nil)
    }
    let deleteSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.deleteSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        api.deleteSession(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteSessionChannel.setMessageHandler(nil)
    }
    let setLoggingEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.asleep_sdk_flutter.AsleepHostApi.setLoggingEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLoggingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        api.setLoggingEnabled(enabled: enabledArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLoggingEnabledChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class EventsStreamHandler: PigeonEventChannelWrapper<NativeEventMessage> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: EventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.asleep_sdk_flutter.AsleepEventChannelApi.events"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NativeEventMessage>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: transportPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
